### ISSUE TITLE
FillIntersection() error

### ISSUE THREAD

**Issue by NguyenVuNguyenPhys** [hanzemeng/MeshSlicerFree#1]
I have tried out the library and encountered some issues with slicing the mesh. Specifically, I have the same mesh and the same cut plane transform for two slicers, Slice1 and Slice2, in the sample scene.

	•	Slice1 is at Position (0,0,0).
	•	Slice2 is at Position (30000,0,1000).

In short, there is no difference between Slice1 and Slice2 except their positions. 

The result is that Slice1 can cut the mesh and fill the intersection area, but Slice2 cannot. When I comment out FillIntersection(), it can slice for both slicers, but there is no mesh for the intersection area.

Could you please help me with this issue?

**Comment by JasonSpine** [comment]
Triangulation is a little buggy in this project.
I've implemented MeshSlicing with this tutorial:
https://www.youtube.com/watch?v=BVCNDUcnE1o
https://github.com/Tvtig/UnityLightsaber

I've improved it quite a bit. And used ``PolygonCollider2D`` ``CreateMesh()`` method to fill intersections: https://docs.unity3d.com/ScriptReference/Collider2D.CreateMesh.html

Sure this algorithm doesn't support submeshes etc., but it's simple, easy to understand and less likely to generate errors.

**Comment by hanzemeng** [comment]
Hi @NguyenVuNguyenPhys, here is my guess on the cause of this issue:
Because double-precision floating-points can only store 15-17 significant digits, vertices in Slice 2 may have lost some precision. The lost of precision leads to the triangulation bug (triangulation is performed in FillIntersection()).

I am currently updating MeshSlicerFree with a better triangulation algorithm. Before that is complete, you can try out @JasonSpine's method, or implement your own triangulation algorithm, or just don't fill the intersection.

**Comment by NguyenVuNguyenPhys** [comment]
> Hi @NguyenVuNguyenPhys, here is my guess on the cause of this issue: Because double-precision floating-points can only store 15-17 significant digits, vertices in Slice 2 may have lost some precision. The lost of precision leads to the triangulation bug (triangulation is performed in FillIntersection()).
> 
> I am currently updating MeshSlicerFree with a better triangulation algorithm. Before that is complete, you can try out @JasonSpine's method, or implement your own triangulation algorithm, or just don't fill the intersection.

Hi @hanzemeng,

   Thank you for the insight and for working on updating the triangulation algorithm in MeshSlicerFree. I appreciate the suggestions you’ve provided and your quick response.  I’ll try out the options you’ve suggested.

Thanks again for your support!

**Comment by NguyenVuNguyenPhys** [comment]
> Triangulation is a little buggy in this project. I've implemented MeshSlicing with this tutorial: https://www.youtube.com/watch?v=BVCNDUcnE1o https://github.com/Tvtig/UnityLightsaber
> 
> I've upgraded it quite a bit. And used `PolygonCollider2D` `CreateMesh()` method to fill intersections: https://docs.unity3d.com/ScriptReference/Collider2D.CreateMesh.html
> 
> Sure this algorithm doesn't support submeshes etc., but it's simple, easy to understand and less likely to generate errors.

Thank @JasonSpine  for sharing your method and the resources. I’ll definitely take a look at the tutorial and the upgraded implementation you’ve mentioned.

Thanks for the helpful tips!

**Comment by JasonSpine** [comment]
My version also separate mesh parts that aren't connected - happens when mesh isn't convex.

![obraz](https://github.com/user-attachments/assets/e1c9b7a3-fd9e-4f06-9c21-d63bf3aed6dc)

![obraz](https://github.com/user-attachments/assets/bc8a0474-8f41-4eec-bfa7-b793ac4284f2)

![obraz](https://github.com/user-attachments/assets/44423a59-d369-4d10-8bc0-c41c0352cb39)

I've implemented it into my project. I didn't make library out of it...

I've seen some non-free assets in the asset store and most of them/all of them would require some adjustments to work with them...

**Comment by NguyenVuNguyenPhys** [comment]
> My version also separate mesh parts that aren't connected - happens when mesh isn't convex.
> 
> ![obraz](https://private-user-images.githubusercontent.com/8041651/362278548-e1c9b7a3-fd9e-4f06-9c21-d63bf3aed6dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTY5MDYsIm5iZiI6MTcyNDk5NjYwNiwicGF0aCI6Ii84MDQxNjUxLzM2MjI3ODU0OC1lMWM5YjdhMy1mZDllLTRmMDYtOWMyMS1kNjNiZjNhZWQ2ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDU0MzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAzMDI4NTY1MmQxMDI4NGVlMDRlMTQ2NTc0ZDUyNjJjNmI0Nzg3MGNlNTMwNzRiMjIyNGNiNjM1MWVjZjk2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yDG0iUHW1kC2RTEjSdMlu8FgiDa0QWYjUpkz7CpY0x4)
> 
> ![obraz](https://private-user-images.githubusercontent.com/8041651/362278926-bc8a0474-8f41-4eec-bfa7-b793ac4284f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTY5MDYsIm5iZiI6MTcyNDk5NjYwNiwicGF0aCI6Ii84MDQxNjUxLzM2MjI3ODkyNi1iYzhhMDQ3NC04ZjQxLTRlZWMtYmZhNy1iNzkzYWM0Mjg0ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDU0MzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFiNjg1YWEyYWJhZTc0Y2ZjNDI4MzUzNmI2MTg3MzNlZmU5NjE4YzFlMTYwMmM0ZjVjNGM5NDIyN2ViMmI3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0DwBhNQ3SNX82d6MBg4UYJ-vX269bLqBRpjTiP7VYj4)
> 
> ![obraz](https://private-user-images.githubusercontent.com/8041651/362279067-44423a59-d369-4d10-8bc0-c41c0352cb39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTY5MDYsIm5iZiI6MTcyNDk5NjYwNiwicGF0aCI6Ii84MDQxNjUxLzM2MjI3OTA2Ny00NDQyM2E1OS1kMzY5LTRkMTAtOGJjMC1jNDFjMDM1MmNiMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDU0MzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU5OTc1YjMzNjA5OGExZThhM2M2ZTg4NWU5ZGIyNWY1NTAyMGQwYzY0YjMwMzgwMmYyNDljOTEyNGEzYWFkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nibOq7J5_ZkyaqmfvELqXVPJo__DCVd8KcNEMLn2fr0)
> 
> I've implemented it into my project. I didn't make library out of it...
> 
> I've seen some non-free assets in the asset store and most of them/all of them would require some adjustments to work with them...

Thank you, @JasonSpine,  I tried out your project and used it for another project—it’s cool. I also managed to cut a mesh that is far from (0,0,0) using @hanzemeng’s library.
 Thank you all very much for your support!
